ansible_connection: ansible.netcommon.network_cli
ansible_network_os: cisco.ios.ios
ansible_command_timeout: 120
# ansible_become=true
# ansible_become_method=ansible.netcommon.enable

floor_level: "Level 6 Inventory group_vars/* CISCO"
